### PR TITLE
Centos8 fixes

### PR DESCRIPTION
**Pull request by cognifloyd**
CentOS 8 needs some fixes (more than other OSes) to run well in docker.
This copies the fixes from https://github.com/ansible-collections/community.mongodb/commit/0a924568b6541d503a2624be0da2c67a88fa1cf6 into this repo.

### CODE REVIEW

**Comment by cognifloyd** [comment]
OK. So far, my test actions run is working: https://github.com/ansible-collections/community.mongodb/commit/0a924568b6541d503a2624be0da2c67a88fa1cf6

Merging this should fix the centos 8 issues.

**Comment by cognifloyd** [comment]
In my test, I ran into two failures. In both cases, the GHA step succeeded with the `latest` mongodb collection, but failed with the released mongodb collection.
https://github.com/cognifloyd/AutomatingMongoDBWithAnsible/runs/3058086067?check_suite_focus=true
https://github.com/cognifloyd/AutomatingMongoDBWithAnsible/runs/3058085789?check_suite_focus=true
So, I recommend:
- a new release of community.mongodb
- merge this PR here

**Comment by rhysmeister** [comment]
OK. Probably about time for another release. I'll probably finish that module and then we can include everything up to that point.

**Comment by rhysmeister** [comment]
It's consistently failing on CI / resync_member_from_tar (2.7, default, requirements.yml). I'd like to sort this before merging if possible. Python 2.7 has suffered from random timeouts on some job but this seems persistent.

**Comment by cognifloyd** [comment]
Yes. It is consistently failing on one of these 3:
- `CI / resync_member_from_tar (2.7, default, requirements.yml) (pull_request)` _I've seen several failures on this one_
- `CI / resync_member_from_tar (3.6, default, requirements.yml) (pull_request)` _this one has been canceled each time the others fail_
- `CI / resync_member_from_tar (3.9, default, requirements.yml) (pull_request)` _I've seen one failure on this one_

However, that's with the released version (`requirements.yml`) of the collection. `latest` always passes.

I'm not sure why fixing the `Dockerfile` makes it break with the released version.

**Comment by rhysmeister** [comment]
```
Run docker exec mongodb-2 sudo systemctl status mongod
  docker exec mongodb-2 sudo systemctl status mongod
  docker exec mongodb-2 sudo systemctl stop mongod
  docker exec mongodb-2 sudo systemctl status mongod
  docker exec mongodb-2 tar czf mongo.tar.gz /var/lib/mongo
  docker exec mongodb-2 sudo systemctl start mongod || docker exec mongodb-2 sudo systemctl status mongod
  docker cp mongodb-2:mongo.tar.gz .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.6/x64
Failed to dump process list for 'mongod.service', ignoring: Input/output error
● mongod.service - MongoDB Database Server
   Loaded: loaded (/usr/lib/systemd/system/mongod.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2021-07-15 06:55:35 UTC; 49s ago
     Docs: https://docs.mongodb.org/manual
  Process: 2890 ExecStart=/usr/bin/mongod $OPTIONS (code=exited, status=0/SUCCESS)
  Process: 2889 ExecStartPre=/usr/bin/chmod 0755 /var/run/mongodb (code=exited, status=0/SUCCESS)
  Process: 2888 ExecStartPre=/usr/bin/chown mongod:mongod /var/run/mongodb (code=exited, status=0/SUCCESS)
  Process: 2887 ExecStartPre=/usr/bin/mkdir -p /var/run/mongodb (code=exited, status=0/SUCCESS)
 Main PID: 2892 (mongod)
   Memory: 283.6M
   CGroup: /system.slice/containerd.service/system.slice/mongod.service

Jul 15 06:55:34 mongodb-2.local systemd[1]: Starting MongoDB Database Server...
Jul 15 06:55:34 mongodb-2.local mongod[2890]: about to fork child process, waiting until server is ready for connections.
Jul 15 06:55:34 mongodb-2.local mongod[2890]: forked process: 2892
Jul 15 06:55:35 mongodb-2.local mongod[2890]: child process started successfully, parent exiting
Jul 15 06:55:35 mongodb-2.local systemd[1]: Started MongoDB Database Server.
Failed to dump process list for 'mongod.service', ignoring: Input/output error
● mongod.service - MongoDB Database Server
   Loaded: loaded (/usr/lib/systemd/system/mongod.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2021-07-15 06:56:26 UTC; 143ms ago
     Docs: https://docs.mongodb.org/manual
  Process: 2890 ExecStart=/usr/bin/mongod $OPTIONS (code=exited, status=0/SUCCESS)
  Process: 2889 ExecStartPre=/usr/bin/chmod 0755 /var/run/mongodb (code=exited, status=0/SUCCESS)
  Process: 2888 ExecStartPre=/usr/bin/chown mongod:mongod /var/run/mongodb (code=exited, status=0/SUCCESS)
  Process: 2887 ExecStartPre=/usr/bin/mkdir -p /var/run/mongodb (code=exited, status=0/SUCCESS)
 Main PID: 2892 (code=exited, status=0/SUCCESS)
   Memory: 188.5M
   CGroup: /system.slice/containerd.service/system.slice/mongod.service

Jul 15 06:55:34 mongodb-2.local mongod[2890]: about to fork child process, waiting until server is ready for connections.
Jul 15 06:55:34 mongodb-2.local mongod[2890]: forked process: 2892
Jul 15 06:55:35 mongodb-2.local mongod[2890]: child process started successfully, parent exiting
Jul 15 06:55:35 mongodb-2.local systemd[1]: Started MongoDB Database Server.
Jul 15 06:56:25 mongodb-2.local systemd[1]: mongod.service: Failed to kill control group /system.slice/containerd.service/system.slice/mongod.service, ignoring: Input/output error
Jul 15 06:56:25 mongodb-2.local systemd[1]: Stopping MongoDB Database Server...
Jul 15 06:56:26 mongodb-2.local systemd[1]: mongod.service: Failed to kill control group /system.slice/containerd.service/system.slice/mongod.service, ignoring: Input/output error
Jul 15 06:56:26 mongodb-2.local systemd[1]: mongod.service: Failed to kill control group /system.slice/containerd.service/system.slice/mongod.service, ignoring: Input/output error
Jul 15 06:56:26 mongodb-2.local systemd[1]: mongod.service: Succeeded.
Jul 15 06:56:26 mongodb-2.local systemd[1]: Stopped MongoDB Database Server.
Error: Process completed with exit code 3.
```

**Comment by rhysmeister** [comment]
@cognifloyd FYI: Added you as a collaborator to this repo. Tried replicating this locally. It works every time so far.

**Comment by rhysmeister** [comment]
@cognifloyd Can we try updating systemd here?

**Comment by cognifloyd** [comment]
updating systemd - that's an interesting idea.

I'm trying to narrow down what is actually failing and then sleep long enough for the other workflows to finish so that I have something to compare it to. If this gives me decent output, then I can start trying to fix the issue.

**Comment by cognifloyd** [comment]
BTW: Here's the documentation for the Dockerfile changes:
https://hub.docker.com/_/centos (See "Systemd integration" section)

>Dockerfile for systemd base image
> ```
> FROM centos:7
> ENV container docker
> RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
> systemd-tmpfiles-setup.service ] || rm -f $i; done); \
> rm -f /lib/systemd/system/multi-user.target.wants/*;\
> rm -f /etc/systemd/system/*.wants/*;\
> rm -f /lib/systemd/system/local-fs.target.wants/*; \
> rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
> rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
> rm -f /lib/systemd/system/basic.target.wants/*;\
> rm -f /lib/systemd/system/anaconda.target.wants/*;
> VOLUME [ "/sys/fs/cgroup" ]
> CMD ["/usr/sbin/init"]
> ```

and

> Running a systemd enabled app container
> In order to run a container with systemd, you will need to mount the cgroups volumes from the host. Below is an example command that will run the systemd enabled httpd container created earlier.
> 
> ```$ docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 local/c7-systemd-httpd```
> This container is running with systemd in a limited context, with the cgroups filesystem mounted. There have been reports that if you're using an Ubuntu host, you will need to add `-v /tmp/$(mktemp -d):/run` in addition to the cgroups mount.

So, I wonder - are we using an ubuntu host? Do we need that /run volume?

**Comment by rhysmeister** [comment]
@cognifloyd Yes, we are running on an Ubuntu host. So I guess we might need /run too.

**Comment by cognifloyd** [comment]
I understand what was happening.

With this PR, where I fixed some systemd+docker initialization:
- the tests consistently pass with the dev (latest) collection, where I dropped the redhat8+docker hacks, but
- only some passed with the stable (1.2.1 release) collection, which still had those hacks.

With the stable collection, you also experienced random failures and timeouts around restarting mongod, so you set `skip_restart: true` as the default.

It turns out that systemd was using a flaky heuristic to guess which process was mongod so it could kill it. When systemd failed to stop mongod and then tried to start a second instance, that of course failed because the port was in use.

Anyway, I found and added one more fix to let systemd know for sure it was running in a container. With this fix systemd consistently failed to ever restart mongod. That's better than whatever flaky heuristic it had been using that only sometimes worked.

Then, I found that some of these playbooks had that same redhat8 docker hack of removing the pidfile. With service Type=forking, systemd can't detect which process is the mongod process without the PIDFile. For debian, they don't use forking, so systemd has no issues detecting which process is their main mongod process.

So, to get these changes working with the stable collection, I had to reverse the PIDFile removal and clean up the orphaned mongod process. Finding the right place to add this was tricky because, as it turns out, yum/dnf was starting the mongod service immediately after each upgrade/downgrade of the mongod package. So I had to make sure to introduce the PIDFile bits before any upgrade/downgrade. I also had to separate the service start/stop from the PIDFile fixes or the playbooks ended up fighting to clean up the orphaned mongod process in multiple places (which became very confusing).

So, here we are. Everything should be working both with stable and with dev playbooks.

I'm tempted to leave a lot of the debug output in place around the service starts and stops so that if another issue pops up we have more insight more quickly. I think the debug messages should be less verbose, but let's not remove them entirely.

In a future PR, once you get confident that you won't be reintroducing the redhat8 docker PIDFile removal hack, then all of the redhat8 PIDFile and orphaned mongod cleanup tasks can be removed.

I'll re-enable the tests shortly to have a full test run through before cleaning up the debug messages.

**Comment by rhysmeister** [comment]
@cognifloyd Great stuff. Thanks for your work.

**Comment by cognifloyd** [comment]
Aargh. There's an issue syncing yum repo data which is breaking the tests.

**Comment by cognifloyd** [comment]
I adjusted the yum_repository tasks to prevent those yum sync failures.

I also split the CI workflow into 5 smaller workflows so that it is easier to restart a section of them. What do you think?

**Comment by cognifloyd** [comment]
K. All tests are finally passing. Merge please! :smile:

**Comment by rhysmeister** [comment]
> I adjusted the yum_repository tasks to prevent those yum sync failures.
> 
> I also split the CI workflow into 5 smaller workflows so that it is easier to restart a section of them. What do you think?

Yes. Good call. That file was a bit hairy and I plan to put in some terraform/aws stuff in the future!

**Pull request merged**
